name: Build platform

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.gif'
      - '.idea/**'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.daemon=false -Xmx5g -Xms5g

jobs:
  verify-mono:
    if: ${{ !contains(github.event.pull_request.head.ref, '#docs') && !(startsWith(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, '#docs')) }}

    runs-on: ubuntu-20.04
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-verify-mono
      cancel-in-progress: true

    outputs:
      version: ${{ steps.properties.outputs.version }}
      release_version: ${{ steps.properties.outputs.release_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Verify code style
        run: ./gradlew --scan detekt

      - name: Verify license headers
        run: ./gradlew --scan spotlessCheck

  test-platform:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-platform-${{ matrix.test_module }}
      cancel-in-progress: true
    strategy:
      matrix:
        test_module: [ 'bridge', 'common', 'core', 'processor:live-view', 'processor:live-instrument', 'storage' ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - uses: docker-practice/actions-setup-docker@master

      - name: Write docker-compose.override.yml
        working-directory: docker/e2e
        run: |
          echo "version: '3.3'" > docker-compose.override.yml
          echo "services:" >> docker-compose.override.yml
          echo "  spp-platform:" >> docker-compose.override.yml
          echo "    environment:" >> docker-compose.override.yml
          echo "      - SPP_PROBE_ENABLED=true" >> docker-compose.override.yml

      - name: Start spp-platform
        run: ./gradlew --scan :platform:assembleUp

      - name: Docker IPs
        run: docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
      - name: Set SPP_PLATFORM_HOST
        run: SPP_PLATFORM_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aqf "name=spp-platform")) && echo "SPP_PLATFORM_HOST=$SPP_PLATFORM_HOST" >> $GITHUB_ENV

      - name: Get access token
        timeout-minutes: 5
        run: until $(curl --output /dev/null --silent --fail http://localhost:12800/api/new-token?authorization_code=change-me); do printf '.'; sleep 5; done && SPP_JWT_TOKEN=$(curl http://localhost:12800/api/new-token?authorization_code=change-me) && echo "SPP_JWT_TOKEN=$SPP_JWT_TOKEN" >> $GITHUB_ENV

      - name: Wait for platform
        timeout-minutes: 5
        run: |
          until $(curl --header "Authorization: Bearer ${{ env.SPP_JWT_TOKEN }}" --output /dev/null --silent --fail http://localhost:12800/health); do printf '.'; sleep 5; done

      - name: Test platform
        run: ./gradlew --scan :platform:${{ matrix.test_module }}:test -Dtest.profile=integration -Dtest.includeSlow=true

      - run: cd docker/e2e && docker-compose logs spp-platform > spp-platform.log
        if: ${{ always() }}

      - name: Set test module name
        if: ${{ always() }}
        run: |
          TEST_MODULE=${{ matrix.test_module }}
          TEST_MODULE=${TEST_MODULE//:/-}
          echo "TEST_MODULE=$TEST_MODULE" >> $GITHUB_ENV
          echo "TEST_MODULE=$TEST_MODULE"

      - name: Upload docker logs artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TEST_MODULE }}-docker.log
          path: docker/e2e/spp-platform.log

      - name: Upload test-live-instrument.log artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-live-instrument.log
          path: /tmp/spp-probe/logs/test-live-instrument.log

      - name: Upload test-live-view.log artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-live-view.log
          path: /tmp/spp-probe/logs/test-live-view.log

  test-probe-jvm:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-probe-jvm
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - uses: docker-practice/actions-setup-docker@master

      - name: Write docker-compose.override.yml
        working-directory: docker/e2e
        run: |
          echo "version: '3.3'" > docker-compose.override.yml
          echo "services:" >> docker-compose.override.yml
          echo "  spp-platform:" >> docker-compose.override.yml
          echo "    environment:" >> docker-compose.override.yml
          echo "      - SPP_PROBE_ENABLED=true" >> docker-compose.override.yml

      - name: Start spp-platform
        run: ./gradlew --scan :platform:assembleUp

      - name: Docker IPs
        run: docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
      - name: Set SPP_PLATFORM_HOST
        run: SPP_PLATFORM_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aqf "name=spp-platform")) && echo "SPP_PLATFORM_HOST=$SPP_PLATFORM_HOST" >> $GITHUB_ENV

      - name: Get access token
        timeout-minutes: 5
        run: until $(curl --output /dev/null --silent --fail http://localhost:12800/api/new-token?authorization_code=change-me); do printf '.'; sleep 5; done && SPP_JWT_TOKEN=$(curl http://localhost:12800/api/new-token?authorization_code=change-me) && echo "SPP_JWT_TOKEN=$SPP_JWT_TOKEN" >> $GITHUB_ENV

      - name: Wait for platform
        timeout-minutes: 5
        run: |
          until $(curl --header "Authorization: Bearer ${{ env.SPP_JWT_TOKEN }}" --output /dev/null --silent --fail http://localhost:12800/health); do printf '.'; sleep 5; done

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Test probe-jvm
        run: |
          ./gradlew --scan -Dtest.profile=integration \
            :probes:jvm:boot:assemble \
            :probes:jvm:boot:test \
            :probes:jvm:common:test \
            :probes:jvm:services:test


  test-probe-nodejs:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-probe-nodejs
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - uses: docker-practice/actions-setup-docker@master

        #todo: shouldn't need SPP_CLIENT_ACCESS_ENABLED=false
      - name: Write docker-compose.override.yml
        working-directory: docker/e2e
        run: |
          echo "version: '3.3'" > docker-compose.override.yml
          echo "services:" >> docker-compose.override.yml
          echo "  spp-platform:" >> docker-compose.override.yml
          echo "    environment:" >> docker-compose.override.yml
          echo "      - SPP_PROBE_ENABLED=true" >> docker-compose.override.yml
          echo "      - SPP_CLIENT_ACCESS_ENABLED=false" >> docker-compose.override.yml

      - name: Start spp-platform
        run: ./gradlew --scan :platform:assembleUp

      - name: Docker IPs
        run: docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
      - name: Set SPP_PLATFORM_HOST
        run: SPP_PLATFORM_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aqf "name=spp-platform")) && echo "SPP_PLATFORM_HOST=$SPP_PLATFORM_HOST" >> $GITHUB_ENV

      - name: Get access token
        timeout-minutes: 5
        run: until $(curl --output /dev/null --silent --fail http://localhost:12800/api/new-token?authorization_code=change-me); do printf '.'; sleep 5; done && SPP_JWT_TOKEN=$(curl http://localhost:12800/api/new-token?authorization_code=change-me) && echo "SPP_JWT_TOKEN=$SPP_JWT_TOKEN" >> $GITHUB_ENV

      - name: Wait for platform
        timeout-minutes: 5
        run: |
          until $(curl --header "Authorization: Bearer ${{ env.SPP_JWT_TOKEN }}" --output /dev/null --silent --fail http://localhost:12800/health); do printf '.'; sleep 5; done

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: probes/nodejs
        run: npm install

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Test probe-nodejs
        run: ./gradlew --scan -p probes/nodejs test
        env:
          CI: true

  test-interface-cli:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-interface-cli
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - uses: docker-practice/actions-setup-docker@master

      - name: Write docker-compose.override.yml
        working-directory: docker/e2e
        run: |
          echo "version: '3.3'" > docker-compose.override.yml
          echo "services:" >> docker-compose.override.yml
          echo "  spp-platform:" >> docker-compose.override.yml
          echo "    environment:" >> docker-compose.override.yml
          echo "      - SPP_PROBE_ENABLED=true" >> docker-compose.override.yml

      - name: Start spp-platform
        run: ./gradlew --scan :platform:assembleUp

      - name: Docker IPs
        run: docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
      - name: Set SPP_PLATFORM_HOST
        run: SPP_PLATFORM_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aqf "name=spp-platform")) && echo "SPP_PLATFORM_HOST=$SPP_PLATFORM_HOST" >> $GITHUB_ENV

      - name: Get access token
        timeout-minutes: 5
        run: until $(curl --output /dev/null --silent --fail http://localhost:12800/api/new-token?authorization_code=change-me); do printf '.'; sleep 5; done && SPP_JWT_TOKEN=$(curl http://localhost:12800/api/new-token?authorization_code=change-me) && echo "SPP_JWT_TOKEN=$SPP_JWT_TOKEN" >> $GITHUB_ENV

      - name: Wait for platform
        timeout-minutes: 5
        run: |
          until $(curl --header "Authorization: Bearer ${{ env.SPP_JWT_TOKEN }}" --output /dev/null --silent --fail http://localhost:12800/health); do printf '.'; sleep 5; done

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build protocol
        run: ./gradlew --scan :protocol:assemble

      - name: Test interface-cli
        run: |
          ./gradlew --scan -Dtest.profile=integration \
            :interfaces:cli:test

      - run: cd docker/e2e && docker-compose logs spp-platform > spp-platform.log
        if: ${{ always() }}

      - name: Upload docker logs artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-interface-cli-platform-logs
          path: docker/e2e/spp-platform.log

  test-interface-jetbrains:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-interface-jetbrains
      cancel-in-progress: true

    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Test interface-jetbrains
        run: |
          ./gradlew --scan \
            :interfaces:jetbrains:commander:test \
            :interfaces:jetbrains:commander:kotlin-compiler-wrapper:test \
            :interfaces:jetbrains:core:test \
            :interfaces:jetbrains:insight:test \
            :interfaces:jetbrains:marker:test \
            :interfaces:jetbrains:marker:js-marker:test \
            :interfaces:jetbrains:marker:jvm-marker:test \
            :interfaces:jetbrains:marker:py-marker:test \
            :interfaces:jetbrains:marker:ult-marker:test \
            :interfaces:jetbrains:plugin:test 


  test-protocol:
#    needs: [ verify-mono ]
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-protocol
      cancel-in-progress: true

    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Test protocol
        run: ./gradlew --scan -p protocol test

  # Delete build artifacts
  cleanup:
    needs:
      - verify-mono
      - test-platform
      - test-probe-jvm
      - test-probe-nodejs
      - test-interface-cli
      - test-interface-jetbrains
      - test-protocol
    runs-on: ubuntu-20.04

    steps:
      - name: Delete spp-platform image
        uses: geekyeggo/delete-artifact@v2
        with:
          name: spp-platform

      - name: Delete spp-platform distribution
        uses: geekyeggo/delete-artifact@v2
        with:
          name: spp-platform-${{ needs.make-distribution.outputs.release_version }}.tar.gz
